Update ElasticsearchEngine.php
ErickTamayo/laravel-scout-elastic pull request #126
Opened 2019-06-07 13:32 UTC by Julinar

fix score order and pagination

2019-06-07 14:22 UTC, ErickTamayo requested changes

2019-06-07 14:22 UTC, ErickTamayo commented on src/ElasticsearchEngine.php
> +        //dd($this->elastic->search($params));
Can you remove this please?

2019-06-07 14:22 UTC, ErickTamayo commented on src/ElasticsearchEngine.php
> +      /*  return $model->getScoutModelsByIds(
Remove this comment as well

2019-06-07 14:23 UTC, ErickTamayo commented
Can you make the test pass again so I can merge this?

2019-06-07 14:28 UTC, Julinar commented on src/ElasticsearchEngine.php
> +        //dd($this->elastic->search($params));
it's removed

2019-06-07 14:28 UTC, Julinar commented on src/ElasticsearchEngine.php
> +      /*  return $model->getScoutModelsByIds(
same

2019-06-10 21:25 UTC, ErickTamayo commented
Sadly this is still failing. I cannot merge until the test is fixed

2019-06-10 21:34 UTC, Julinar commented
> Sadly this is still failing. I cannot merge until the test is fixed

Well tbh it's my first contrib on github and I didnt know why the test fail.
I checked on my branch and the return is :

```
Array
(
    [index] => scout
    [type] => table
    [body] => Array
        (
            [query] => Array
                (
                    [bool] => Array
                        (
                            [must] => Array
                                (
                                    [0] => Array
                                        (
                                            [query_string] => Array
                                                (
                                                    [query] => *zonda*
                                                )
                                        )
                                    [1] => Array
                                        (
                                            [match_phrase] => Array
                                                (
                                                    [foo] => 1
                                                )
                                        )
                                    [2] => Array
                                        (
                                            [terms] => Array
                                                (
                                                    [bar] => Array
                                                        (
                                                            [0] => 1
                                                            [1] => 3
                                                        )
                                                )
                                        )
                                )
                        )
                )
            [track_scores] => 1
            [sort] => Array
                (
                    [id] => Array
                        (
                            [order] => desc
                        )
                )
        )
)
```

for the test : 

```
    public function test_search_sends_correct_parameters_to_elasticsearch()
    {
        $client = Mockery::mock('Elasticsearch\Client');
        $client->shouldReceive('search')->with([
            'index' => 'scout',
            'type' => 'table',
            'body' => [
                'query' => [
                    'bool' => [
                        'must' => [
                            ['query_string' => ['query' => '*zonda*']],
                            ['match_phrase' => ['foo' => 1]],
                            ['terms' => ['bar' => [1, 3]]],
                        ]
                    ], 
                ],
                'track_scores' => 1,
                'sort' => [
                    ['id' => ['order' => 'desc']]
                ]
            ]
        ]);
```

If you have an idea of why test test fail I take it :)

2020-11-26 20:27 UTC, closed without merging