Major overhaul
ErickTamayo/laravel-scout-elastic pull request #40
Opened 2017-02-21 18:56 UTC by thomasjsn

* Own config file
* Implemented orderBy
* Console commands for viewing/creating indices and mapping
* Elasticsearch specific search method

2017-02-21 18:58 UTC, thomasjsn commented
Oh... I've used some PHP 7 specific functions... Too soon to require PHP7?

2017-02-22 07:50 UTC, thomasjsn commented
This PR solves #36, #38 and #39.

2017-02-24 16:50 UTC, ErickTamayo commented
@thomasjsn sorry for the delay I've been on a personal matter that needs to be addressed I will review/test it in the weekend

2017-02-28 09:39 UTC, thomasjsn commented
@ErickTamayo I've made a `IsElasticSearchable` interface, which I use when iterating models. Want me to add it? Doesn't really require any testing anyways.

2017-03-01 16:19 UTC, ErickTamayo commented
@thomasjsn sure you can include it, I'm planning to review this today and think of new features that we can add to it.

2017-03-02 08:21 UTC, thomasjsn commented
@ErickTamayo Sure, I'll add it this evening.

2017-03-03 19:49 UTC, huglester commented
This PR is really VERY huge improvement. Currently working with it.
But for example I search for tag:
"hello", some items get high scoring, all of them, but scoring is:
9.98
9.97 and so on...

But what if I want only those with 'hello' keyword - and order by 'created_at' field.

and this high scoring is not of a big help... that's main issue why I would like to 'disable' default sorting.


thanks for ideas

2017-03-03 20:02 UTC, thomasjsn commented
@huglester What I do is map tags as an array of text or keywords. The I search in that field only: `tags:hello`. Then the scoring will be the same for all documents that has "hello" in the tags array. And then order by the `orderBy` attribute.

2017-03-03 21:05 UTC, huglester commented
Hello @thomasjsn  and thanks for letting know.

so my initial example was:
```php
'sort' => [
                    [
                        'created_at' => [
                            'order' => 'desc',
                        ],
                        'id' => [
                            'order' => 'desc',
                        ],
                    ],
                ],
                'query' => [
                    'bool' => [
                        'must' => [
                            'term' => ['uri' => $query],
                        ],
                    ],
                ],
```

so basicly sort part is solved now?

But I am not sure on how to search the tag now?
I mean trying along these lines:
```php
$articles = \Webas\ProfilesModule\Entities\Profile::elasticSearch('multi_match', 'uri:Some-Url', [
            'fields' => ['uri'],
        ])->get();
```

But I also need BOOL must stuff

Thank you

2017-03-03 21:33 UTC, thomasjsn commented
I often just do a `query_string` search with `field:query`. That is the default, unless you have modified the config.

```php
Project::search('tags:mytag`)->orderBy->('created_at')->get();
```

You can not include the `field:` in a `multi_match` search. That only works with `query_string`.

So either `query_string` with the search phrase `tags:something` or `multi_match` with search phrase `something` and set the fields property, as you have done.

It helps to familiarize oneself a bit with the different search methods that ElasticSearch provides.

ElasticSearch is extremely configurable, so it's a bit tricky to write a search method that will suit all needs.  You can quite easily write your own trait to tailor the search method exactly like you want. Like I have done for counting, see #42. The you can define the search, filters, ordering and everything like you want it.

2017-03-03 22:25 UTC, huglester commented
I see @thomasjsn 
Thanks again, I think I managed to solve this. There were some indices generated incorrectly which were causing different problems.

Thank you this 42 example. It's good to be able to pass custom queries like so!

2017-03-07 15:27 UTC, VRuzhentsov commented
What can we do, to merge this PR?

2017-03-07 15:29 UTC, ErickTamayo commented
I'm updating homestead right now to test this. So very likely today :)

On Tue, Mar 7, 2017 at 11:27 AM Vitalii Ruzhentsov <notifications@github.com>
wrote:

What can we do, to merge this PR?

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/ErickTamayo/laravel-scout-elastic/pull/40#issuecomment-284753841>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AEkSUSyKOdxFkrNWmlZAyHo_TVC39Ozrks5rjXdigaJpZM4MHuCO>
.

-- 
Erick Tamayo

2017-03-07 17:20 UTC, huglester commented
if that matters, I am currently playing this @thomasjsn fork - and not met any problems. VERY HAPPY :)

2017-03-07 17:38 UTC, thomasjsn commented
I've been using it on my production site for about 2 weeks now ☺️

2017-03-07 17:42 UTC, huglester commented
I am not using in production. but for around a week in development. and very happy user!

2017-03-07 23:08 UTC, ErickTamayo requested changes

2017-03-07 23:08 UTC, ErickTamayo commented on src/ElasticSearchable.php
> +trait ElasticSearchable
I'm not totally agree with making a new trait for it. I understand the `elasticSearch` method to be able to customize the search but as this is a driver it has to be something that must comply with the current usage of Scout using the `Searchable` trait.

We might need to get around the `searchableWithin` method, for example a public property in the Model makes more sense here and then in the Engine just make a ternary.

I guess we can have the trait but we need to make it the `ElasticsearchEngine` to work out of the box with the `Searchable` trait.

2017-03-07 23:08 UTC, ErickTamayo commented on config/elasticsearch.php
> +<?php
we can have the configuration inside scout.php I would like to have every driver config in the same scout config file.

2017-03-07 23:08 UTC, ErickTamayo commented on src/ElasticsearchEngine.php
> +                    '_index' => $model->searchableWithin(),
As I mentioned in trait, we need to make able to work "out of the box" with the Scout `Searchable` trait

2017-03-08 15:25 UTC, VRuzhentsov commented on src/ElasticSearchable.php
> +trait ElasticSearchable
is it ok, that all mapping in this trait is overriding by toSearchableArray() method?

2017-03-09 08:46 UTC, thomasjsn commented
Anyone interested, feel free to make the requested changes. For my own need I will be focusing more on Elastic Search specific methods, and less on compliance with searching through Scout.

2017-03-09 08:51 UTC, huglester commented
I must agree with @thomasjsn 

Probably some improvements could be made. But the problem with scout is that it is bound to Algolia. you can control lot of stuff in algolia web interface and so on.

Elasticsearch is different. There are different versions etc, since this is separate package, I think it can give some improvements over original Scout. And if separe Trait is used, I do not see any harm.

Sometimes making tool to 'agnotic' you loose 80% of funtionality and you are left with the 'basics':
like lets search for "dog" in the index and return results.

But who uses elasticsearch, probably has more needs than basic search, and needs more control over search.

thank you

2017-03-09 10:40 UTC, VRuzhentsov commented
@thomasjsn 
Can you please open issues tracker in yours fork?
maybe, i just dont wanna flude in main repository

i have couple of ideas to improve, and questions.

at this moment, origin method toSearchableArray() overrides ES mappings in yours mappings() method, while reindexing all. is it ok?
I'm still dealing with the correct configuration of the model. 

although i found, that Scout+ES is incompatible with Eloquent\Model::toArray() method, because if we are store model with it relations in ES, method toArray() anyway reloading model relations from DB. I suggest simply override it with converting to  (array)$model.
What do you think?

2017-03-09 10:44 UTC, VRuzhentsov commented
But it deals, in case, if we store full model with it attributes and relations

2017-03-13 08:16 UTC, thomasjsn commented
@VRuzhentsov Issues opened.

2017-03-16 16:30 UTC, reinierkors commented
@thomasjsn I can't get the search ordering to work, I'm using the following:
`$videos = Video::search($query)->orderBy('publishedAt', 'desc')->paginate(5);`

Do you know what could cause this?

2017-03-16 16:31 UTC, ErickTamayo commented
@reinierkors please open a issue in the fork, this PR is getting bloated with non-related questions about the pr itself.

2017-09-18 15:34 UTC, closed without merging